allowBuilds:
  lefthook: true
  sharp: false
  'unrs-resolver': false

minimumReleaseAgeExclude:
  - lucide-react@1.29.0
  - shadcn@4.16.2
  - '@oxlint/binding-android-arm-eabi@1.86.0'
  - '@oxlint/binding-android-arm64@1.86.0'
  - '@oxlint/binding-darwin-arm64@1.86.0'
  - '@oxlint/binding-darwin-x64@1.86.0'
  - '@oxlint/binding-freebsd-x64@1.86.0'
  - '@oxlint/binding-linux-arm-gnueabihf@1.86.0'
  - '@oxlint/binding-linux-arm-musleabihf@1.86.0'
  - '@oxlint/binding-linux-arm64-gnu@1.86.0'
  - '@oxlint/binding-linux-arm64-musl@1.86.0'
  - '@oxlint/binding-linux-ppc64-gnu@1.86.0'
  - '@oxlint/binding-linux-riscv64-gnu@1.86.0'
  - '@oxlint/binding-linux-riscv64-musl@1.86.0'
  - '@oxlint/binding-linux-s390x-gnu@1.86.0'
  - '@oxlint/binding-linux-x64-gnu@1.86.0'
  - '@oxlint/binding-linux-x64-musl@1.86.0'
  - '@oxlint/binding-openharmony-arm64@1.86.0'
  - '@oxlint/binding-win32-arm64-msvc@1.86.0'
  - '@oxlint/binding-win32-ia32-msvc@1.86.0'
  - '@oxlint/binding-win32-x64-msvc@1.86.0'
  - oxlint-plugin-eslint@1.86.0
  - oxlint@1.86.0
